### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by rawtaz** [addinall/COBWEB#2]
Is there any guide or similar on how to actually use this? :)

**Comment by addinall** [comment]
Not really.  You need to get the GNU COBOL cross compiler working.  Set up Apache2 to allow CGI scripts and run compiled code as a CGI executable.  I never meant to use it in anger.  Someone told me it was "impossible" to code a HTML5 compliant web page in COBOL.  Cheers!

**Comment by wmealing** [comment]
Thems fighting words!

**Comment by rawtaz** [comment]
There is no way to argue neither with nor against what has already been said. Out of sheer respect and appreciation, I am closing this issue 🙇
